on: 
  push: 
    branches: [main]
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - uses: nobe4/action-ln@go-release
        with:
          noop: false
          config: ln-config.yaml
          app_id: ${{ secrets.ACTION_LN_APP_ID }}
          app_private_key: ${{ secrets.ACTION_LN_APP_PRIVATE_KEY }}
          app_install_id: ${{ secrets.ACTION_LN_APP_INSTALL_ID }}
