on: 
  - push
  - workflow_dispatch
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nobe4/action-ln@create-pull
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_LN_TOKEN }}
