on: 
  push: 
    branches: [main]
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  link:
    runs-on: ubuntu-latest
    steps:    
      - uses: nobe4/action-ln@e3f127a6e9c0cf85f6e08040caa6f32cb112fcb8
        with:
          token: ${{ secrets.ACTION_LN_TOKEN }}
