on: 
  push: 
    branches: [main]
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  link:
    runs-on: ubuntu-latest
    steps:    
      - uses: nobe4/action-ln@edge
        with:
          noop: false
          config-path: ln-config.yaml
          #token: ${{ secrets.ACTION_LN_TOKEN }}
          app-id: ${{ secrets.ACTION_LN_APP_ID }}
          app-private-key: ${{ secrets.ACTION_LN_APP_PRIVATE_KEY }}
          app-install-id: ${{ secrets.ACTION_LN_APP_INSTALL_ID }}
