on: 
  push: 
    branches: [main]
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  link:
    runs-on: ubuntu-latest
    steps:    
      - uses: nobe4/action-ln@edge
        with:
          noop: true
          config: ln-config.yaml
          token: ${{ secrets.ACTION_LN_TOKEN }}
